### ISSUE TITLE
ESM format seems not supported?

### ISSUE THREAD

**Issue by davidsneighbour** [absolute-version/commit-and-tag-version#147]
I don't know if this is a bug or maybe a future feature: using a config that is in the ESM format leads to errors:

```bash
❯ npm run release

> @davidsneighbour/kollitsch-dev@2024.1.32 release
> npm run release:patch


> @davidsneighbour/kollitsch-dev@2024.1.32 release:patch
> commit-and-tag-version --release-as patch --sign -a -t "v" --releaseCommitMessageFormat "chore(release): v{{currentTag}}" && ./bin/repo/hooks/postrelease

/home/patrick/github.com/davidsneighbour/kollitsch.dev/node_modules/commit-and-tag-version/lib/configuration.js:20
    const jsConfiguration = require(configPath);
                            ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/patrick/github.com/davidsneighbour/kollitsch.dev/.versionrc.js from /home/patrick/github.com/davidsneighbour/kollitsch.dev/node_modules/commit-and-tag-version/lib/configuration.js not supported.
Instead change the require of .versionrc.js in /home/patrick/github.com/davidsneighbour/kollitsch.dev/node_modules/commit-and-tag-version/lib/configuration.js to a dynamic import() which is available in all CommonJS modules.
    at module.exports.getConfiguration (/home/patrick/github.com/davidsneighbour/kollitsch.dev/node_modules/commit-and-tag-version/lib/configuration.js:20:29)
    at Object.<anonymous> (/home/patrick/github.com/davidsneighbour/kollitsch.dev/node_modules/commit-and-tag-version/command.js:153:11) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.12.2
```

Does the package understand the config in ESM format and if not is it possible to add this as a feature?

**Comment by amoshydra** [comment]
change `.versionrc.js` to `.versionrc.cjs`.

this package support cjs extension

**Comment by amoshydra** [comment]
I have mistook the issue as about "supporting Package type=module environment".

I have checked the source code, mjs is not supported as the config is always imported via `require`. See: https://github.com/absolute-version/commit-and-tag-version/blob/7ebdacd6edd26076eabed753cdcf3070142f5f0d/lib/configuration.js#L19-L20

I guess this would be a feature request.

Off the top of my head, it will need to use dynamic import to load an ESM config and making the code flow async.

**Comment by TimothyJones** [comment]
I agree, I think this is a feature request. It would definitely be good to have the ability to use ESM for the config.

I believe it would (almost) come for free if we upgraded it to typescript, so I'll tag #29

**Comment by gian1200** [comment]
Similar to how other projects handle config files (e.g. [commitlint](https://commitlint.js.org/reference/configuration.html)), maybe you can leverage [cosmiconfig](https://github.com/cosmiconfig/cosmiconfig#searchplaces) to handle these (and other config file formats.

**Comment by TimothyJones** [comment]
Sound sensible to me

**Comment by MikeDabrowski** [comment]
+1 for this. I wanted to use custom updater and needed to use external package in it. That package is only mjs so I had to resort to `execSync` its cli instead.

**Comment by TimothyJones** [comment]
This is now available in 13.1.0
